# Generated by Django 5.2.16 on 2026-08-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a general restaurant review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem'),
        ),
    ]
