# Generated by Django 5.2.16 on 2026-07-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='Guest', help_text="Name for this booking (e.g. the guest's name)", max_length=100),
            preserve_default=False,
        ),
    ]
