# Generated by Django 5.2.16 on 2026-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Spice Route Restaurant', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short catchy line shown on homepage', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='restaurant/')),
            ],
            options={
                'verbose_name': 'Restaurant Profile',
                'verbose_name_plural': 'Restaurant Profile',
            },
        ),
    ]
