# Generated by Django 5.2.16 on 2026-08-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_gallery/')),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('general', 'General')], default='general', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restaurantprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
